---
include:
  - project: "open-source/gitlab-ci-templates"
    ref: "branch/v2"
    file:
      - "templates/base.yml"
      - "templates/no-duplicated-ci-pipelines.yml"
      - "templates/create-release-on-heptapod.yml"
      - "templates/build-docker-image.yml"

default:
  tags:
    - dedibox