---
include:
  - project: "open-source/gitlab-ci-templates"
    ref: "branch/v2"
    file:
      - "templates/base.yml"
      - "templates/no-duplicated-ci-pipelines.yml"
      - "templates/create-release-on-heptapod.yml"
      - "templates/build-docker-image.yml"

default:
  tags:
    - dedibox

variables:
  POETRY_VIRTUALENVS_PATH: $CI_PROJECT_DIR/venv

.base:
  image: python:3.11-alpine
  before_script:
    - pip install -U poetry
    - poetry install --only=dev
  cache:
    paths:
      - venv

.base-all:
  image: python:3.11-alpine
  before_script:
    - apk add --update --no-cache gcc g++ python3-dev unixodbc-dev
    - pip install -U poetry
    - poetry install --with=dev
  cache:
    paths:
      - venv

black:
  extends: .base
  stage: lint
  script:
    - poetry run black sls_api tests

py3:
  extends: .base-all
  stage: tests
  script:
    - cp config.ini.default config.ini
    - poetry run pytest -v tests
  artifacts: null
