---
include:
  - project: "open-source/gitlab-ci-templates"
    ref: "branch/v2"
    file:
      - "templates/base.yml"
      - "templates/no-duplicated-ci-pipelines.yml"
      - "templates/create-release-on-heptapod.yml"
      - "templates/build-docker-image.yml"

default:
  tags:
    - dedibox

variables:
  POETRY_VIRTUALENVS_PATH: $CI_PROJECT_DIR/venv

.base-all:
  image: astral/uv:python3.11-trixie-slim
  before_script:
    - apt-get update
    - apt-get install -y gcc g++ python3-dev unixodbc-dev
  cache:
    paths:
      - venv

black:
  stage: lint
  image: astral/uv:python3.11-trixie-slim
  script:
    - uvx black sls_api tests

py3:
  stage: tests
  image: astral/uv:python3.11-trixie-slim
  before_script:
    - apt-get update
    - apt-get install -y gcc g++ python3-dev unixodbc-dev
    - uv sync --locked
    - cp config.ini.default config.ini
  script:
    - uv run pytest -v tests
  artifacts: null
